apiVersion: v1
kind: Service
metadata:
  name: wholesale-api-service
  namespace: wholesale
spec:
  type: LoadBalancer
  selector:
    app: wholesale-api
  ports:
    - port: 80
      targetPort: 3000
